### ISSUE TITLE
Issue reading an LTA generated by fMRIPrep

### ISSUE THREAD

**Issue by oesteban** [poldracklab/nitransforms#64]
[This LTA file](https://github.com/poldracklab/nitransforms/files/4347227/T1_robustreg.txt) ([generated by this node](https://github.com/poldracklab/smriprep/blob/b5b74ad2dbd54284f36ca843829ec38014637c2a/smriprep/workflows/outputs.py#L238)) fails to load:
```Python
>>> import nitransforms as nit
>>> xfm = nit.linear.load('T1_robustreg.lta', fmt='lta')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oesteban/workspace/nitransforms/nitransforms/linear.py", line 455, in load
    filename, fmt=fmt, reference=reference, moving=moving
  File "/home/oesteban/workspace/nitransforms/nitransforms/linear.py", line 198, in from_filename
    return cls(matrix, reference=reference)
  File "/home/oesteban/workspace/nitransforms/nitransforms/linear.py", line 236, in __init__
    for xfm in transforms
  File "/home/oesteban/workspace/nitransforms/nitransforms/linear.py", line 236, in <listcomp>
    for xfm in transforms
  File "/home/oesteban/workspace/nitransforms/nitransforms/linear.py", line 70, in __init__
    raise ValueError("Matrix does not represent a valid transform.")
ValueError: Matrix does not represent a valid transform.
```

**Comment by oesteban** [comment]
BTW - that transform, as per fMRIPrep, translates to ITK as [this file](https://github.com/poldracklab/nitransforms/files/4347270/sub-01_from-fsnative_to-T1w_mode-image_xfm.txt) - we should add a test checking idempotence (i.e., lta <-> itk <-> lta).

**Comment by oesteban** [comment]
It seems this is still failing at "/home/oesteban/workspace/nitransforms/nitransforms/linear.py", line 70.
